### ISSUE TITLE
About the purpose of Webflux

### ISSUE THREAD

**Issue by HelloTo4x** [anicetkeric/webflux-otp#8]
Hi, i am reading your project, can u tell me the purpose of Webflux, reactive in your project ? Is it for increasing performance, can u tell me some disadvantaged of Webflux ?

**Comment by anicetkeric** [comment]
Hi @HelloTo4x ,
I'm using Webflux in this project on the backend side. It makes it easy to program non-blocking (asynchronous) streams that handle data I/O.

**Comment by HelloTo4x** [comment]
yes, i know it but i really don't know why you need use Non-blocking IO in your project

**Comment by anicetkeric** [comment]
For this example project, I wanted to highlight the integration of Spring Security in reactive webflux. 

You can check my post for more explanation

https://boottechnologies-ci.medium.com/spring-webflux-security-otp-email-with-mongodb-and-flutter-1-2-f73e1d94ec7a

**Comment by HelloTo4x** [comment]
thank u so much
